
name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Decrypt GPG file
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GCP_CREDENTIALS_ENCRYPTION_KEY }}" --output ./service-account.json service-account.json.gpg
    - name: Set terraform credentials location
      run:
        echo "GOOGLE_APPLICATION_CREDENTIALS=./service-account.json" >> $GITHUB_ENV
    - name: Set project name
      run:
        echo "TF_VAR_google_project_name=${{ secrets.TF_VAR_google_project_name }}" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Plan
      run: terraform plan -input=false
    - name: Print event_name vars
      run: echo ${{ github.event_name }}
    - name: Print ref_name var
      run: echo ${{ github.ref_name }}
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref_name == 'main'
      run: terraform apply -auto-approve -input=false